[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/discover"
  to = "/discover/index.html"
  status = 200

[[redirects]]
  from = "/discover/quiz"
  to = "/discover/quiz/index.html"
  status = 200

[[redirects]]
  from = "/discover/result"
  to = "/discover/result/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
